dist: focal

arch:
  - amd64

services:
  - docker

os: linux

language: php

php:
  - 8.0

env:
  - RUNTIME=node-17.0
    PHP_CLASS=Node170
    ENTRYPOINT=tests.js
  - RUNTIME=deno-1.14
    PHP_CLASS=Deno114
    ENTRYPOINT=tests.ts
  - RUNTIME=python-3.10
    PHP_CLASS=Python310
    ENTRYPOINT=tests.py
  - RUNTIME=dart-2.15
    PHP_CLASS=Dart215
    ENTRYPOINT=tests.dart
  - RUNTIME=ruby-3.1
    PHP_CLASS=Ruby31
    ENTRYPOINT=tests.rb
  - RUNTIME=php-8.0
    PHP_CLASS=PHP80
    ENTRYPOINT=tests.php

notifications:
  email:
    - team@appwrite.io

before_install:
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi

install:
  - docker --version
  - composer install

script:
  - RUNTIME=${RUNTIME} PHP_CLASS=${PHP_CLASS} ENTRYPOINT=${ENTRYPOINT} sh tests.sh
