dist: focal

arch:
  - amd64

# services:
#   - docker

os: linux

language: php

php:
  - 8.0

env:
#   - RUNTIME=deno-1.14
  - RUNTIME=node-17.0
    PHP_CLASS=Node170

notifications:
  email:
    - team@appwrite.io

before_install:
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi

install:
  - docker --version
  - composer install

script:
  - cd runtimes/${RUNTIME}
  - docker build -t open-runtimes/test-runtime .
  - cd ../../
  - cd tests/${RUNTIME}
  - docker run --rm -d --name open-runtimes-test -v $(pwd):/usr/code:rw -v $(pwd):/tmp:ro -e INTERNAL_RUNTIME_KEY=test-secret-key -p 3000:3000 open-runtimes/test-runtime sh -c "sh /usr/local/src/build.sh && sh /usr/local/src/start.sh"
  - sleep 5
  - docker ps
  - docker logs open-runtimes-test
  - cd ../../
  - INTERNAL_RUNTIME_KEY=test-secret-key vendor/bin/phpunit tests/${PHP_CLASS}.php