dist: focal

arch:
  - amd64

# services:
#   - docker

os: linux

language: php

php:
  - 8.0

env:
  - RUNTIME=deno-1.14
  - RUNTIME=node-17.0

notifications:
  email:
    - team@appwrite.io

before_install:
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi

install:
  - docker --version
  - composer install

script:
  - cd runtimes/${RUNTIME} && docker-compose up -d && cd ../../
  - RUNTIME=${RUNTIME} INTERNAL_RUNTIME_KEY=secret-key vendor/bin/phpunit tests/RuntimeTest.php
