dist: focal

arch:
  - amd64

services:
  - docker

os: linux

language: php

php:
  - 8.0

env:
  # Node
  - RUNTIME=node-17.0
    PHP_CLASS=Node170
    ENTRYPOINT=tests.js
  - RUNTIME=node-16.0
    PHP_CLASS=Node160
    ENTRYPOINT=tests.js
  - RUNTIME=node-15.5
    PHP_CLASS=Node155
    ENTRYPOINT=tests.js
  - RUNTIME=node-14.5
    PHP_CLASS=Node145
    ENTRYPOINT=tests.js

  # Deno
  - RUNTIME=deno-1.14
    PHP_CLASS=Deno114
    ENTRYPOINT=tests.ts
  - RUNTIME=deno-1.13
    PHP_CLASS=Deno113
    ENTRYPOINT=tests.ts
  - RUNTIME=deno-1.12
    PHP_CLASS=Deno112
    ENTRYPOINT=tests.ts

  # Python
  - RUNTIME=python-3.10
    PHP_CLASS=Python310
    ENTRYPOINT=tests.py
  - RUNTIME=python-3.9
    PHP_CLASS=Python39
    ENTRYPOINT=tests.py
  - RUNTIME=python-3.8
    PHP_CLASS=Python38
    ENTRYPOINT=tests.py

  # Dart
  - RUNTIME=dart-2.15
    PHP_CLASS=Dart215
    ENTRYPOINT=tests.dart
  - RUNTIME=dart-2.14
    PHP_CLASS=Dart214
    ENTRYPOINT=tests.dart
  - RUNTIME=dart-2.13
    PHP_CLASS=Dart213
    ENTRYPOINT=tests.dart
  - RUNTIME=dart-2.12
    PHP_CLASS=Dart212
    ENTRYPOINT=tests.dart

  # Ruby
  - RUNTIME=ruby-3.1
    PHP_CLASS=Ruby31
    ENTRYPOINT=tests.rb
  - RUNTIME=ruby-3.0
    PHP_CLASS=Ruby30
    ENTRYPOINT=tests.rb

  # PHP
  - RUNTIME=php-8.0
    PHP_CLASS=PHP80
    ENTRYPOINT=tests.php
  - RUNTIME=php-8.1
    PHP_CLASS=PHP81
    ENTRYPOINT=tests.php

notifications:
  email:
    - team@appwrite.io

before_install:
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi

install:
  - docker --version
  - composer install

script:
  - export RUNTIME=${RUNTIME}; export PHP_CLASS=${PHP_CLASS}; export ENTRYPOINT=${ENTRYPOINT}; sh tests.sh
