dist: focal

arch:
  - amd64

services:
  - docker

os: linux

language: php

php:
  - 8.0

vm:
  size: large

env:
  global:
    - VERSION=v3
  jobs:
    # Node
    - RUNTIME=node-18.0
      TEST_CLASS=Base
      ENTRYPOINT=tests.js
      IMAGE=openruntimes/node:${VERSION}-18.0
      ARCH=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND="npm install"
      START_COMMAND="npm start"
    - RUNTIME=node-18.0
      TEST_CLASS=Base
      ENTRYPOINT=tests.mjs
      IMAGE=openruntimes/node:${VERSION}-18.0
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND="npm install"
      START_COMMAND="npm start"

    # Deno
    - RUNTIME=deno-1.24
      TEST_CLASS=Base
      ENTRYPOINT=tests.ts
      IMAGE=openruntimes/deno:${VERSION}-1.24
      ARCH=linux/amd64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND="deno cache tests.ts"
      START_COMMAND="denon start"

    # Python
    - RUNTIME=python-3.10
      TEST_CLASS=Base
      ENTRYPOINT=tests.py
      IMAGE=openruntimes/python:${VERSION}-3.10
      ARCH=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND="pip install --no-cache-dir -r requirements.txt"
      START_COMMAND="python3 src/server.py"

    # Dart
    - RUNTIME=dart-2.18
      TEST_CLASS=Base
      ENTRYPOINT=lib/tests.dart
      IMAGE=openruntimes/dart:${VERSION}-2.18
      ARCH=linux/amd64,linux/arm64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND="dart pub get"
      START_COMMAND="/usr/local/server/src/function/server"

    # Ruby
    - RUNTIME=ruby-3.1
      TEST_CLASS=Base
      ENTRYPOINT=tests.rb
      IMAGE=openruntimes/ruby:${VERSION}-3.1
      ARCH=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND=""
      START_COMMAND="bundle exec puma -b tcp://0.0.0.0:3000 -e production"

    # PHP
    - RUNTIME=php-8.1
      TEST_CLASS=Base
      ENTRYPOINT=tests.php
      IMAGE=openruntimes/php:${VERSION}-8.1
      ARCH=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND="composer update --no-interaction --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"
      START_COMMAND="php src/server.php"

    # Swift
    - RUNTIME=swift-5.5
      TEST_CLASS=Base
      ENTRYPOINT=Tests.swift
      IMAGE=openruntimes/swift:${VERSION}-5.5
      ARCH=linux/amd64,linux/arm64
      TEST_SCRIPT=tests-v3.sh

    # Kotlin
    - RUNTIME=kotlin-1.6
      TEST_CLASS=Base
      ENTRYPOINT=Tests.kt
      IMAGE=openruntimes/kotlin:${VERSION}-1.6
      ARCH=linux/amd64,linux/arm64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND=""
      START_COMMAND="java -jar /usr/local/server/src/function/kotlin-runtime-1.0.0.jar"

    # Java
    - RUNTIME=java-18.0
      TEST_CLASS=Base
      ENTRYPOINT=Tests.java
      IMAGE=openruntimes/java:${VERSION}-18.0
      ARCH=linux/amd64,linux/arm64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND=""
      START_COMMAND="java -jar /usr/local/server/src/function/java-runtime-1.0.0.jar"

    # C++
    - RUNTIME=cpp-17
      TEST_CLASS=Base
      ENTRYPOINT=tests.cc
      IMAGE=openruntimes/cpp:${VERSION}-17
      ARCH=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      TEST_SCRIPT=tests-v3.sh

    # DotNet
    - RUNTIME=dotnet-6.0
      TEST_CLASS=Base
      ENTRYPOINT=Tests.cs
      IMAGE=openruntimes/dotnet:${VERSION}-6.0
      ARCH=linux/amd64,linux/arm64
      TEST_SCRIPT=tests.sh
      BUILD_COMMAND=""
      START_COMMAND="dotnet DotNetRuntime.dll"

    # Go
    # - RUNTIME=go-1.19
    #   TEST_CLASS=Base
    #   ENTRYPOINT=tests.go
    #   IMAGE=openruntimes/go:${VERSION}-1.19
    #   ARCH=linux/amd64,linux/arm64
    #   TEST_SCRIPT=tests.sh

notifications:
  email:
    - team@appwrite.io

before_install:
  # Upgrade Docker
  - docker version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  # Login to Docker Hub
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi
  # Install Docker buildx
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  # Activate Docker buildx
  - docker buildx create --use

install:
  - docker version
  - composer install

script:
  - export BUILD_COMMAND=${BUILD_COMMAND}; export START_COMMAND=${START_COMMAND}; export RUNTIME=${RUNTIME}; export TEST_CLASS=${TEST_CLASS}; export ENTRYPOINT=${ENTRYPOINT}; sh ${TEST_SCRIPT}

deploy:
  - provider: script
    edge: true
    script: export RUNTIME=${RUNTIME}; ARCH=${ARCH}; export IMAGE=${IMAGE}; sh deploy.sh
    on:
      tags: true