version: '3'

services:
  open-runtimes-cpp-17:
    container_name: open-runtimes-cpp-17
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - OPEN_RUNTIMES_SECRET
      - OPEN_RUNTIMES_ENTRYPOINT
    volumes:
      - ./example/:/usr/code:rw
    command: sh -c "sh /usr/local/src/build.sh && cp /usr/code/code.tar.gz /tmp/code.tar.gz && sh /usr/local/src/start.sh"