version: '3'

services:
  open-runtimes-php-8.1:
    container_name: open-runtimes-php-8.1
    build:
      context: .
    ports: 
      - 3000:3000
    environment:
      - INTERNAL_RUNTIME_KEY
      - INTERNAL_RUNTIME_ENTRYPOINT
      - BUILD_COMMAND
      - START_COMMAND
    volumes:
      - ./example/:/mnt/code:rw
    command: sh -c "sh helpers/build.sh \"$BUILD_COMMAND\" && sh helpers/start.sh \"$START_COMMAND\""