version: '3'

services:
  open-runtimes-swift:
    container_name: open-runtimes-swift
    build:
      context: .
    ports: 
      - "3000:3000"
    environment:
      - OPEN_RUNTIMES_SECRET
      - BUILD_COMMAND
      - START_COMMAND
    volumes:
      - ./example/:/mnt/code:rw
    command: sh -c "sh helpers/build.sh \"$BUILD_COMMAND\" && sh helpers/start.sh \"$START_COMMAND\""